version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    restart: always

  webapp:
    image: nginx:alpine
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always 